### ISSUE TITLE
attached image files aren't displayed anymore

### ISSUE THREAD

**Issue by npwhite** [dispersal/CMPUT404-project-socialdistribution#132]
on /frontend/posts/create/, when you attach an image it doesn't say which images are currently attached anymore, the posting all works and everything, so this is just a minor frontend bug

**Comment by MichaelParadis** [comment]
I am pretty sure this has to do with the content of the post not including
the image link anymore. Can you look into this?

**Comment by npwhite** [comment]
@MichaelParadis posting images still works (at least on the source_origin fix branch), and the linking  seems to be working?
